version = 1

exclude_patterns = [
  "dist/**",
  "vendor/**"
]

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

[[transformers]]
name = "php-cs-fixer"
enabled = true