#!/usr/bin/env bash
#
# Automated release script for novaramedia-com theme.
# Runs the full release flow non-interactively:
#   1. Validates branch state
#   2. Runs release-it (bumps version, updates changelog, builds, updates style.css)
#   3. Commits all changes as "Build: x.x.x"
#   4. Optionally creates PR to master
#
# Usage:
#   ./scripts/release.sh [increment] [--pr]
#
#   increment: major | minor | patch (default: minor)
#   --pr:      create PR to master without prompting
#
# Examples:
#   ./scripts/release.sh                # minor bump, prompt for PR
#   ./scripts/release.sh patch          # patch bump, prompt for PR
#   ./scripts/release.sh minor --pr     # minor bump, auto-create PR
#   ./scripts/release.sh --pr           # minor bump, auto-create PR

set -euo pipefail

INCREMENT="minor"
AUTO_PR=false

for arg in "$@"; do
  case "$arg" in
    --pr) AUTO_PR=true ;;
    major|minor|patch) INCREMENT="$arg" ;;
    *) echo "Unknown argument: $arg"; exit 1 ;;
  esac
done
BRANCH=$(git branch --show-current)

# --- Preflight checks ---

if [ "$BRANCH" != "development" ]; then
  echo "Error: Must be on 'development' branch (currently on '$BRANCH')"
  exit 1
fi

if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "Error: Working tree has uncommitted changes. Commit or stash them first."
  exit 1
fi

echo "Pulling latest development..."
git pull --ff-only origin development

# --- Run release-it ---

echo ""
echo "Running release-it --ci --increment=$INCREMENT ..."
echo ""
npx release-it "$INCREMENT" --ci

# --- Read new version ---

VERSION=$(node -p "require('./package.json').version")
echo ""
echo "Version bumped to $VERSION"

# --- Commit ---

echo ""
echo "Committing all changes as 'Build: $VERSION' ..."
git add -A
git commit -m "Build: $VERSION"

echo ""
echo "Pushing development..."
git push origin development

# --- Create PR ---

CREATE_PR=false
if [ "$AUTO_PR" = true ]; then
  CREATE_PR=true
elif [ -t 0 ]; then
  echo ""
  read -r -p "Create PR to master? [y/N] " REPLY
  [[ "$REPLY" =~ ^[Yy]$ ]] && CREATE_PR=true
fi

if [ "$CREATE_PR" = true ]; then
  CHANGELOG_ENTRY=$(sed -n "/^## \[$VERSION\]/,/^## \[/p" CHANGELOG.md | sed '$d')

  gh pr create \
    --base master \
    --head development \
    --title "Release $VERSION" \
    --body "$(cat <<EOF
## Release $VERSION

$CHANGELOG_ENTRY

---
Generated by \`scripts/release.sh\`
EOF
)"

  echo ""
  echo "PR created. Review and merge when ready to deploy."
else
  echo ""
  echo "Skipped PR creation. To create manually:"
  echo "  gh pr create --base master --head development --title 'Release $VERSION'"
fi

echo ""
echo "Release $VERSION complete."
