#!/usr/bin/env bash
#
# Automated release script for novaramedia-com theme.
# Runs the full release flow non-interactively:
#   1. Validates branch state
#   2. Runs release-it (bumps version, updates changelog, builds, updates style.css)
#   3. Commits all changes as "Build: x.x.x"
#   4. Optionally creates PR to master
#
# Usage:
#   ./scripts/release.sh [increment]
#
#   increment: major | minor | patch (default: minor)
#
# Examples:
#   ./scripts/release.sh           # minor bump (4.4.0 → 4.5.0)
#   ./scripts/release.sh patch     # patch bump (4.4.0 → 4.4.1)
#   ./scripts/release.sh major     # major bump (4.4.0 → 5.0.0)

set -euo pipefail

INCREMENT="${1:-minor}"
BRANCH=$(git branch --show-current)

# --- Preflight checks ---

if [ "$BRANCH" != "development" ]; then
  echo "Error: Must be on 'development' branch (currently on '$BRANCH')"
  exit 1
fi

if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "Error: Working tree has uncommitted changes. Commit or stash them first."
  exit 1
fi

echo "Pulling latest development..."
git pull --ff-only origin development

# --- Run release-it ---

echo ""
echo "Running release-it --ci --increment=$INCREMENT ..."
echo ""
npx release-it "$INCREMENT" --ci

# --- Read new version ---

VERSION=$(node -p "require('./package.json').version")
echo ""
echo "Version bumped to $VERSION"

# --- Commit ---

echo ""
echo "Committing all changes as 'Build: $VERSION' ..."
git add -A
git commit -m "Build: $VERSION"

echo ""
echo "Pushing development..."
git push origin development

# --- Create PR ---

echo ""
read -r -p "Create PR to master? [y/N] " CREATE_PR
if [[ "$CREATE_PR" =~ ^[Yy]$ ]]; then
  CHANGELOG_ENTRY=$(sed -n "/^## \[$VERSION\]/,/^## \[/p" CHANGELOG.md | sed '$d')

  gh pr create \
    --base master \
    --head development \
    --title "Release $VERSION" \
    --body "$(cat <<EOF
## Release $VERSION

$CHANGELOG_ENTRY

---
Generated by \`scripts/release.sh\`
EOF
)"

  echo ""
  echo "PR created. Review and merge when ready to deploy."
else
  echo ""
  echo "Skipped PR creation. To create manually:"
  echo "  gh pr create --base master --head development --title 'Release $VERSION'"
fi

echo ""
echo "Release $VERSION complete."
