#!/usr/bin/env bash
#
# Automated release script for novaramedia-com theme.
# Runs the full release flow non-interactively:
#   1. Validates branch state
#   2. Runs release-it (bumps version, updates changelog, builds, updates style.css)
#   3. Commits all changes as "Build: x.x.x"
#   4. Optionally creates PR to master
#
# Usage:
#   ./scripts/release.sh [increment] [--pr] [--hotfix]
#
#   increment: major | minor | patch (default: minor)
#   --pr:      create PR to master without prompting
#   --hotfix:  release from a hotfix/* branch cut from master instead of
#              development; forces a patch increment. See docs/releases.md
#              for the full hotfix flow including the back-merge step.
#
# Examples:
#   ./scripts/release.sh                # minor bump, prompt for PR
#   ./scripts/release.sh patch          # patch bump, prompt for PR
#   ./scripts/release.sh minor --pr     # minor bump, auto-create PR
#   ./scripts/release.sh --pr           # minor bump, auto-create PR
#   ./scripts/release.sh --hotfix --pr  # patch release from hotfix/* branch

set -euo pipefail

INCREMENT="minor"
AUTO_PR=false
HOTFIX=false

for arg in "$@"; do
  case "$arg" in
    --pr) AUTO_PR=true ;;
    --hotfix) HOTFIX=true ;;
    major|minor|patch) INCREMENT="$arg" ;;
    *) echo "Unknown argument: $arg"; exit 1 ;;
  esac
done
BRANCH=$(git branch --show-current)

# --- Preflight checks ---

if [ "$HOTFIX" = true ]; then
  if [[ "$BRANCH" != hotfix/* ]]; then
    echo "Error: --hotfix must run from a 'hotfix/*' branch cut from master (currently on '$BRANCH')"
    exit 1
  fi

  if [ "$INCREMENT" != "patch" ]; then
    echo "Note: --hotfix forces a patch increment"
    INCREMENT="patch"
  fi
elif [ "$BRANCH" != "development" ]; then
  echo "Error: Must be on 'development' branch (currently on '$BRANCH')"
  exit 1
fi

if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "Error: Working tree has uncommitted changes. Commit or stash them first."
  exit 1
fi

# 'git add -A' below sweeps untracked files into the Build commit, so refuse
# to run while any exist.
if git status --porcelain | grep -q '^??'; then
  echo "Error: Untracked files present. 'git add -A' would commit them. Remove or gitignore them first:"
  git status --porcelain | grep '^??'
  exit 1
fi

if git rev-parse --abbrev-ref --symbolic-full-name '@{u}' >/dev/null 2>&1; then
  echo "Pulling latest $BRANCH..."
  git pull --ff-only origin "$BRANCH"
else
  # release-it refuses to run without an upstream; fresh hotfix branches
  # don't have one yet, so push to create it.
  echo "No upstream set — pushing $BRANCH to origin..."
  git push -u origin "$BRANCH"
fi

# --- Run release-it ---

echo ""
echo "Running release-it --ci --increment=$INCREMENT ..."
echo ""
npx release-it "$INCREMENT" --ci

# --- Read new version ---

VERSION=$(node -p "require('./package.json').version")
echo ""
echo "Version bumped to $VERSION"

# --- Commit ---

echo ""
echo "Committing all changes as 'Build: $VERSION' ..."
git add -A
git commit -m "Build: $VERSION"

echo ""
echo "Pushing $BRANCH..."
git push -u origin "$BRANCH"

# --- Create PR ---

CREATE_PR=false
if [ "$AUTO_PR" = true ]; then
  CREATE_PR=true
elif [ -t 0 ]; then
  echo ""
  read -r -p "Create PR to master? [y/N] " REPLY
  [[ "$REPLY" =~ ^[Yy]$ ]] && CREATE_PR=true
fi

TITLE="Release: $VERSION"
[ "$HOTFIX" = true ] && TITLE="Release: $VERSION (hotfix)"

if [ "$CREATE_PR" = true ]; then
  CHANGELOG_ENTRY=$(sed -n "/^## \[$VERSION\]/,/^## \[/p" CHANGELOG.md | sed '$d')

  gh pr create \
    --base master \
    --head "$BRANCH" \
    --title "$TITLE" \
    --body "$(cat <<EOF
## Release $VERSION

$CHANGELOG_ENTRY

---
Generated by \`scripts/release.sh\`
EOF
)"

  echo ""
  echo "PR created. Review and merge when ready to deploy."
else
  echo ""
  echo "Skipped PR creation. To create manually:"
  echo "  gh pr create --base master --head $BRANCH --title '$TITLE'"
fi

if [ "$HOTFIX" = true ]; then
  echo ""
  echo "After the PR is merged and deployed, back-merge into development:"
  echo "  git fetch origin"
  echo "  git checkout development && git pull --ff-only origin development"
  echo "  git merge origin/master && git push origin development"
fi

echo ""
echo "Release $VERSION complete."
